### ISSUE TITLE
dependencies / documentation to run the experiments?

### ISSUE THREAD

**Issue by flint-xf-fan** [zilunpeng/svrg_for_policy_evaluation_with_fewer_gradients#1]
Hi, thank you for the great work! Is it possible to provide a simple documentation on how to run the experiments? Thanks!

**Comment by zilunpeng** [comment]
Thank you for your interests! Please give me a few days to clean up the code and upload a documentation.

**Comment by flint-xf-fan** [comment]
Thank you in advance and take your time at your convenience :) 

I wan to see if I can make use of your idea of SCSG for policy evaluation in my ongoing project. It would be great if your documentation can help demonstrate how can I quickly test if I can adapt it for my project. Thanks again!

**Comment by zilunpeng** [comment]
I'm really sorry about the wait. I have updated the documentation.

**Comment by flint-xf-fan** [comment]
Thank you!
